name: Bug report
description: 反馈问题
labels: bug
body:
- type: input
  id: issue_link
  attributes:
    label: "可复现的链接："
    description: "一个最小化的重现能让我们精确地定位问题，从而快速解决问题。如何创建，点击 v3：[codesandbox](https://codesandbox.io/s/vue-template-916h0)、[jsrun](https://jsrun.net/vIyKp/edit) 或 v4：[codesandbox](https://codesandbox.io/s/vxe-table-wentiyanshi-forked-54v2j)、[jsrun](https://jsrun.net/K5IKp/edit)，编辑后保存。"
  validations:
    required: true
- type: textarea
  id: issue_describe
  attributes:
    label: "问题描述与截图："
  validations:
    required: true
- type: markdown
  attributes:
    value: "在发布问题之前，请仔细阅读所填写的步骤，以确保是详细和清晰的。"
- type: input
  id: issue_expect
  attributes:
    label: "期望的结果："
- type: input
  id: issue_os_version
  attributes:
    label: "操作系统："
    placeholder: "例如：window10"
- type: input
  id: issue_browser_version
  attributes:
    label: "浏览器版本："
    placeholder: "例如：chrome 95.0.4638.69"
